[package]
name = "scylla-cdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.48"
scylla = "0.3.0"
tokio = { version = "1.1.0", features = ["rt", "io-util", "net", "time", "macros", "sync"] }
chrono = "0.4.19"
futures = "0.3.17"
uuid = "0.8.2"
num_enum = "0.5.4"

[dev-dependencies]
hex = "0.4.3"
